# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('dama', ['core', 'network'])
    module.source = [
        'model/damanetdevice.cc',
        'model/damamac.cc',
        'model/damacontroller.cc',
        'model/damachannel.cc',
        'model/simplebroadcastmac.cc',
        'model/simplebroadcastchannel.cc',
        'model/tdmacontroller.cc',
        'model/ralohacontroller.cc',
        'helper/distribuited-dama-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('dama')
    module_test.source = [
        'test/dama-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'dama'
    headers.source = [
        'model/damanetdevice.h',
        'model/damamac.h',
        'model/damacontroller.h',
        'model/damachannel.h',
        'model/simplebroadcastmac.h',
        'model/simplebroadcastchannel.h',
        'model/tdmacontroller.h',
        'model/ralohacontroller.h',
        'helper/distribuited-dama-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

